path: C:/Users/arn18/Documents/GitHub/40.-MIT--Fire-Flame-and-Smoke-Detection # dataset root dir
train: images/train # train images (relative to 'path')
val: images/train # val images (relative to 'path')

# Classes
names:
  0: fire
